// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPbZqGb-5av1XI8IUR-45USOeWfq6Jn-M',
    appId: '1:31566576594:web:5a05c1e8511aab3206260b',
    messagingSenderId: '31566576594',
    projectId: 'finalkbdwala',
    authDomain: 'finalkbdwala.firebaseapp.com',
    storageBucket: 'finalkbdwala.appspot.com',
    measurementId: 'G-0Y5LRCHGTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCw4V9lniInZx6QaFxGdJkqfQEq4m7fy4',
    appId: '1:31566576594:android:505ba2388ba68c7b06260b',
    messagingSenderId: '31566576594',
    projectId: 'finalkbdwala',
    storageBucket: 'finalkbdwala.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMHNn2Tr5DI8CASwe9rsEF1UCTNavqPEs',
    appId: '1:31566576594:ios:eaec49020accfd0a06260b',
    messagingSenderId: '31566576594',
    projectId: 'finalkbdwala',
    storageBucket: 'finalkbdwala.appspot.com',
    iosClientId: '31566576594-c35hrocln4gd4bp4mn13g7j534n4f9u4.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalKbdWala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMHNn2Tr5DI8CASwe9rsEF1UCTNavqPEs',
    appId: '1:31566576594:ios:eaec49020accfd0a06260b',
    messagingSenderId: '31566576594',
    projectId: 'finalkbdwala',
    storageBucket: 'finalkbdwala.appspot.com',
    iosClientId: '31566576594-c35hrocln4gd4bp4mn13g7j534n4f9u4.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalKbdWala',
  );
}
